# Generated by Django 4.2.5 on 2023-10-12 08:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0002_alter_patient_db_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report_db",
            name="Template",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
