# Generated by Django 4.2.5 on 2023-10-17 12:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0003_alter_report_db_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patientreports_db",
            fields=[
                (
                    "Patientid",
                    models.IntegerField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("Pathologist", models.CharField(max_length=20)),
                ("Template", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
