# Generated by Django 4.2.5 on 2023-10-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0004_patientreports_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientreports_db",
            name="Patientid",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
